### PR TITLE
Fix reading ssl key and cert from string.

### PR DESCRIPTION
**Pull request by danhper**
The `key` option was not working, so I fixed it.
See http://erlang.org/doc/man/ssl.html for more info.
I also added a dummy key and cert to be able to add tests.

### CODE REVIEW

**Comment by zepplock** [comment]
This is weird since I know I have cert/keys and it is working for me. What was the issue exactly?

**Comment by danhper** [comment]
Using the following config:

``` elixir
  pools: [
    test: [
      env: :dev,
      cert: File.read!(Path.expand("../priv/certs/debug-cert.pem", __DIR__)),
      key: File.read!(Path.expand("../priv/certs/debug-key.pem", __DIR__))
    ]
  ]
```

I get the following errror

```
failed to connect to push socket gateway.sandbox.push.apple.com:2195, reason given: {:options, {:key, <<48, 130, 4, 163, 2, 1, 0, 2, 130, 1, 1, 0, 187, 41, 238, 50, 232, 183, 200, 43, 221, 250, 33, 183, 161, 238, 123, 108, 161, 123, 229, 176, 172, 103, 174, 219, 145, 94, 133, 223, 124, 187, 194, 114, 41, 154, 96, 130, ...>>}}
```

The `debug-cert.pem` and `debug-key.pem` are generated as follow:

``` sh
# debug.p12 is the exported APNS certificate containing the private key
openssl pkcs12 -in debug.p12 -out debug.pem -nodes -clcerts
openssl rsa -in debug.pem -out debug-key.pem
openssl x509 -in debug.pem -out debug-cert.pem
```

Here is how to reproduce in a clean iex session:

``` iex
> Application.ensure_all_started(:ssl)
> [{:Certificate, cert_der, _}] = :public_key.pem_decode(File.read!("./debug-cert.pem"))
> [{:RSAPrivateKey, key_der, _}] = :public_key.pem_decode(File.read!("./debug-key.pem"))
> {:ok, socket} = :ssl.connect('gateway.sandbox.push.apple.com', 2195, cert: cert_der, key: key_der)
** (MatchError) no match of right hand side value: {:error, {:options, {:key, <<48, 130, 4, 163, 2, 1, 0, 2, 130, 1, 1, 0, 187, 41, 238, 50, 232, 183, 200, 43, 221, 250, 33, 183, 161, 238, 123, 108, 161, 123, 229, 176, 172, 103, 174, 219, 145, 94, 133, 223, 124, 187, 194, 114, 41, 154, 96, ...>>}}}
> {:ok, socket} = :ssl.connect('gateway.sandbox.push.apple.com', 2195, cert: cert_der, key: {:RSAPrivateKey, key_der})
{:ok,
 {:sslsocket, {:gen_tcp, #Port<0.2030>, :tls_connection, :undefined},
  #PID<0.82.0>}}
> :ssl.close(socket)
:ok
```

As you can see, the version with only a binary as `:key` option fails with a match error, which conforms to the  `:ssl` documentation. The version with `RSAPrivateKey` connects normally.

Now, in master branch, if I put a `IO.inspect(opts)` in `APNS.Sender.connect_socket`, which displays the options directly passed to `:ssl.connect`, I get the following:

```
[cert: <<48, 130, 5, 143, 48, 130, 4, 119, 160, 3, 2, 1, 2, 2, 8, 95, 226, 160, 49, 235, 143, 87, 207, 48
, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 5, 5, 0, 48, 129, 150, 49, 11, 48, 9, 6, 3, 85, 4, ...>>, 
 key: <<48, 130, 4, 163, 2, 1, 0, 2, 130, 1, 1, 0, 187, 41, 238, 50, 232, 183, 200, 43, 221, 250, 33, 183
, 161, 238, 123, 108, 161, 123, 229, 176, 172, 103, 174, 219, 145, 94, 133, 223, 124, 187, 194, 114, 41, 
154, 96, 130, ...>>,
```

so `:key` is a binary and therefore does not work.

Please let me know if I am missing something, thank you!

**Comment by zepplock** [comment]
I don't get those messages. 

If I use your keys in this branch, I get TLS errors `16:32:16.660 [error] [APNS] #PID<0.248.0> failed to connect to push socket gateway.sandbox.push.apple.com:2195, reason given: {:tls_alert, 'certificate unknown'}`

If I use my production key/cert on `master` branch I get all tests working. 

Can you please try it with key/cert generated by Apple Dev Center?

**Comment by danhper** [comment]
> If I use your keys in this branch

The certificate is not meant to really connect to APNS, it would be unsafe to add a real certificate to GitHub.
I added them to be able to test the ssl configuration, but it is a dummy certificate, so getting `certificate unknown` makes sense.

> If I use my production key/cert on master branch I get all tests working.

There are currently no tests for the `cert` and `key` options, which is why I think tests are working.

> Can you please try it with key/cert generated by Apple Dev Center?

I did, and the master branch does not work with the `cert` and `key` options for me.

Could you please try the following steps please.
1. Add a valid `.pem` certificate as `priv/certs/dev.pem`
2. Run the following commands
   - `openssl rsa -in priv/certs/dev.pem  -out priv/certs/dev-key.pem`
   - `openssl x509 -in priv/certs/dev.pem  -out priv/certs/dev-cert.pem`
3. Change the `config.exs` file to look like this
   
   ``` elixir
     # certfile: {:apns, "certs/dev.pem"},
     cert: File.read!(Path.expand("../priv/certs/dev-cert.pem", __DIR__)),
     key: File.read!(Path.expand("../priv/certs/dev-key.pem", __DIR__)),
   ```
4. Try to run `iex -S mix` and check the logs in both branches.

Using my branch, I got a successful log:

```
13:29:16.320 [debug] [APNS] #PID<0.290.0> successfully connected to gateway.sandbox.push.apple.com:2195

13:29:16.320 [debug] [APNS] #PID<0.290.0> successfully connected to socket
```

Using master branch, I got:

```
13:28:31.427 [warn]  [APNS] #PID<0.155.0> unable to connect to socket, backing off

13:28:31.427 [error] [APNS] #PID<0.156.0> failed to connect to push socket gateway.sandbox.push.apple.com
:2195, reason given: {:options, {:key, <<48, 130, 4, 163, 2, 1, 0, 2, 130, 1, 1, 0, 187, 41, 238, 50, 232
, 183, 200, 43, 221, 250, 33, 183, 161, 238, 123, 108, 161, 123, 229, 176, 172, 103, 174, 219, 145, 94, 1
33, 223, 124, 187, 194, 114, 41, 154, 96, 130, ...>>}}
```

Please let me know if you get the same result, or if I am missing something here.

Thank you!

**Comment by thousandsofthem** [comment]
current released version don't work for me as well. `certfile` is ok and `key`/`cert` is failing

@zepplock if it works for you, could you provide some code example?
i.e. how to generate keys, exact apns config

**Comment by zepplock** [comment]
@thousandsofthem could you please try @tuvistavie fork and let me know if his change fixes it for you? If it does i will merge it.

I have a certificate and keys from Apple. Both `.pem` files with Base64 encoded data inside.

**Comment by thousandsofthem** [comment]
`.pem` files can be generated differently and have different format despite same extension.
`apns4ex` is asking for specific format for private key - 
https://github.com/chvanikoff/apns4ex/blob/master/lib/apns/ssl_configuration.ex#L49
 otherwise failing on this line. 
@tuvistavie 's fork works for me (tried connecting and actually sending messages) while current master throws errors (certfile option works, cert/key is not)

**Comment by zepplock** [comment]
Ok, will merge and update today. Thanks for help and sorry for a delay.

**Comment by danhper** [comment]
Thanks! :smile:

**Comment by danhper** [comment]
@zepplock Could you push the update to hex so that I can switch back to the hex dependency please?
Thanks :smile:

**Comment by zepplock** [comment]
Actually I don't have right to push hex updates but I will ping @chvanikoff to do it.

**Comment by danhper** [comment]
Great, thank you!

**Pull request merged**
