### PR TITLE
Add synchronous call

### PR DESCRIPTION
**Pull request by danhper**
Currently, there was only an async version of `push`.
I would like to use a synchronous version, as I am already making it async somewhere else,
and recording notifications that processed correctly.
This does not touch any existing API, simply adding a sync version of `push`.

Thank you.

### CODE REVIEW

**Comment by zepplock** [comment]
Need extra pair of eyes to review this PR

**Comment by danhper** [comment]
Ping :smile:

**Comment by zepplock** [comment]
Merging, sorry for a delay. Will bump version after we figure out https://github.com/chvanikoff/apns4ex/pull/44

**Comment by danhper** [comment]
No problem, thank you for merging!
I replied to the other PR.

**Pull request merged**
