### PR TITLE
update dependences

### PR DESCRIPTION
**Pull request by oamado**

### CODE REVIEW

**Comment by zepplock** [comment]
What about people still using poison 2.x? Shouldn't it be `{:poison, "~> 1.5 or ~> 2.0 or ~> 3.0"},`

**Comment by oamado** [comment]
@zepplock if we leave the two last versions? `{:poison, "~> 2.2 or ~> 3.0"}`

**Comment by zepplock** [comment]
@oamado look at #56, I have all 3 versions and it seems to work in my setup. Can you please verify?

**Comment by oamado** [comment]
outdated

**Pull request closed without merging**
